name = "candidlabs-site"
compatibility_date = "2026-02-09"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "candidlabs-site-db"
database_id = "PASTE_REAL_D1_DATABASE_ID_HERE"

c66b00777634f4581ba77edb5371322"

[vars]
ALLOWED_DOMAIN = "ALLOWED_DOMAIN"
SESSION_SECRET = "SESSION_SECRET"
